# .github/workflows/release.yml
name: Build & Release (Windows)

on:
  push:
    tags: ['v*.*.*']

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # ВАЖНО: не указывать cache: 'npm', раз нет lock-файла

      - name: Install deps
        run: npm install --no-audit --no-fund

      # (если у тебя есть шаг с зеркалом/кешем Electron — оставляй)
      - name: Build & Publish to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-builder --win nsis portable -p always
