name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-win:
    runs-on: windows-latest

    env:
      # Кэшированные каталоги electron/electron-builder (ускоряет сборку и снижает обрывы скачиваний)
      ELECTRON_CACHE: ${{ runner.temp }}\electron-cache
      ELECTRON_BUILDER_CACHE: ${{ runner.temp }}\electron-builder

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      # === Опционально: сделать ICO из PNG (если icon.ico отсутствует) ===
      # ВАЖНО: тут явный шелл pwsh и ПРАВИЛЬНО расставленные скобки вокруг Test-Path.
      - name: Make ICO from PNG (optional)
        shell: pwsh
        run: |
          if ((Test-Path 'build/icon.png') -and -not (Test-Path 'build/icon.ico')) {
            Write-Host "icon.ico not found, generating from icon.png..."
            npx png-to-ico build/icon.png | Out-File -FilePath build/icon.ico -Encoding Byte
          } else {
            Write-Host "icon.png or icon.ico condition not met — skipping ICO generation."
          }

      - name: Build & Publish to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          npx electron-builder --win nsi
