name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Без lock-файла используем npm install (а не npm ci)
      - name: Install deps
        run: |
          npm install --no-audit --no-fund

      # Опционально: делаем ICO из PNG, если PNG есть и ICO ещё нет
      - name: Make ICO from PNG (optional)
        shell: pwsh
        run: |
          if ( (Test-Path 'build/icon.png') -and -not (Test-Path 'build/icon.ico') ) {
            node -e "require('png-to-ico')('build/icon.png').then(b=>require('fs').writeFileSync('build/icon.ico', b)).catch(e=>{console.error(e); process.exit(1)})"
            Write-Host 'icon.ico создан из icon.png'
          } else {
            Write-Host 'icon.png не найден или icon.ico уже существует — пропускаем'
          }

      - name: Build & Publish to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx electron-builder --win nsis portable -p always
