name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-win:
    runs-on: windows-latest

    # Кэш и зеркала для стабильных скачиваний Electron
    env:
      ELECTRON_CACHE: ${{ runner.temp }}\electron-cache
      ELECTRON_BUILDER_CACHE: ${{ runner.temp }}\electron-builder
      ELECTRON_MIRROR: https://github.com/electron/electron/releases/download/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Если у тебя НЕТ package-lock.json — используем npm install (а не npm ci)
      - name: Install deps
        run: npm install

      # Генерация ICO из PNG при необходимости (PowerShell, правильная проверка)
      - name: Make ICO from PNG (optional)
        shell: pwsh
        run: |
          if ((Test-Path 'build/icon.png') -and -not (Test-Path 'build/icon.ico')) {
            echo "PNG найден, ICO отсутствует — генерирую..."
            npx png-to-ico build/icon.png | Set-Content -Encoding Byte build/icon.ico
          } else {
            echo "Шаг пропущен: либо нет PNG, либо ICO уже существует."
          }

      - name: Build & Publish to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # встроенный токен Actions
        run: |
          npx electron-builder --win nsis portable -p always
